Spectron integration tests config
Cryptonomic/T2 pull request #214
Opened 2020-08-19 19:10 UTC by JacekWalczak92

2020-08-20 14:40 UTC, anonymoussprocket requested changes

2020-08-20 14:40 UTC, anonymoussprocket commented on src/components/BalanceBanner/index.tsx
> +                        <TezosAddress id="tezosAddres" address={delegatedAddress} color="white" size={ms(-1)} weight={300} />
spelling

2020-08-20 14:40 UTC, anonymoussprocket commented on src/containers/LoginCreate/index.tsx
> +        if (ipcRenderer.sendSync('is-spectron')) {
Does this code need to live in the release?

2020-08-20 14:40 UTC, anonymoussprocket commented on tsconfig.json
> +    "./test", "test"
is this duplicated?

2020-08-20 14:40 UTC, anonymoussprocket commented on test/spec.js
> +const assert = require('assert');
tests should be organized in a directory structure similar to the code. Consider how ConseilJS does it: [code](https://github.com/Cryptonomic/ConseilJS/tree/master/src) vs [tests](https://github.com/Cryptonomic/ConseilJS/tree/master/test).

2021-05-07 12:14 UTC, vishakh commented
Closing in favor of #346.

2021-05-07 12:14 UTC, closed without merging